[ANDON-L1]
TIME1=8:03
TIME2=10:00
TIME3=10:10
TIME4=12:00
TIME5=13:00
TIME6=15:00
TIME7=15:10
TIME8=17:10
TIME9=17:30
TIM10=19:50

[ANDON-L4]
TIME1=8:03
TIME2=10:00
TIME3=10:10
TIME4=12:00
TIME5=13:00
TIME6=15:00
TIME7=15:10
TIME8=17:10
TIME9=17:30
TIM10=18:30
[TaktTime]
L1=6.3
L4=4.7

[ANDON]
; 无呼叫时滚动显示的原文内容（可在此修改，不填则使用 app.config 中的 Andon_text_str）
Text=三不原则：不接受不良；不制造不良；不流出不良

[DB]
USER=
PWD=
ConnStr=Data Source=XYDLT-PE-001\SQLEXPRESS;Initial Catalog=MES_XY_OTR;User ID=sa;Password=XYDLT123@;Connect Timeout=3;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
